### ISSUE TITLE
Replace Hively cross-section with Bosch-Hale

### ISSUE THREAD

**Issue by tbody-cfs** [cfs-energy/cfspopcon#43]
Is there any reason why the Hively cross-section is being used?

![image](https://github.com/cfs-energy/cfspopcon/assets/116750897/77337f45-08e1-4f05-98d6-cec312d5e73e)

**Comment by tbody-cfs** [comment]
Also need to check the other rate coefficients

![image](https://github.com/cfs-energy/cfspopcon/assets/116750897/74dc1f09-4c66-4559-8e04-a05107aff856)

**Comment by hassec** [comment]
> Is there any reason why the Hively cross-section is being used?

@tbody-cfs has this been answered? Do we want to make this change or should we close this issue?

**Comment by tbody-cfs** [comment]
#101
